//
// Created by Homin Su on 2022/2/19.
//

#ifndef HTP_PLATFORM_MACHINE_ROBOT_APP_MACHINE_ROBOT_INTERNAL_SERVICE_ROBOT_IMPL_H_
#define HTP_PLATFORM_MACHINE_ROBOT_APP_MACHINE_ROBOT_INTERNAL_SERVICE_ROBOT_IMPL_H_



class RobotImpl {

};



#endif //HTP_PLATFORM_MACHINE_ROBOT_APP_MACHINE_ROBOT_INTERNAL_SERVICE_ROBOT_IMPL_H_
