// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: v1/response.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 执行完成，发送当前坐标到后端
type MoveDoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`                                // x
	Y         float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`                                // y
	Z         float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`                                // z
	Rx        float64 `protobuf:"fixed64,4,opt,name=rx,proto3" json:"rx,omitempty"`                              // 绕 x 角度
	Ry        float64 `protobuf:"fixed64,5,opt,name=ry,proto3" json:"ry,omitempty"`                              // 绕 y 角度
	Check     bool    `protobuf:"varint,6,opt,name=check,proto3" json:"check,omitempty"`                         // 是否为检查动作
	Delay     float64 `protobuf:"fixed64,7,opt,name=delay,proto3" json:"delay,omitempty"`                        // 每个动作的延时
	Uuid      string  `protobuf:"bytes,8,opt,name=uuid,proto3" json:"uuid,omitempty"`                            // 设备的唯一识别码
	CheckName string  `protobuf:"bytes,9,opt,name=check_name,json=checkName,proto3" json:"check_name,omitempty"` // 检查动作名称
}

func (x *MoveDoneRequest) Reset() {
	*x = MoveDoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDoneRequest) ProtoMessage() {}

func (x *MoveDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDoneRequest.ProtoReflect.Descriptor instead.
func (*MoveDoneRequest) Descriptor() ([]byte, []int) {
	return file_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *MoveDoneRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveDoneRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveDoneRequest) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *MoveDoneRequest) GetRx() float64 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *MoveDoneRequest) GetRy() float64 {
	if x != nil {
		return x.Ry
	}
	return 0
}

func (x *MoveDoneRequest) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *MoveDoneRequest) GetDelay() float64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *MoveDoneRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MoveDoneRequest) GetCheckName() string {
	if x != nil {
		return x.CheckName
	}
	return ""
}

// 响应
type MoveDoneReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *MoveDoneReply) Reset() {
	*x = MoveDoneReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveDoneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDoneReply) ProtoMessage() {}

func (x *MoveDoneReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDoneReply.ProtoReflect.Descriptor instead.
func (*MoveDoneReply) Descriptor() ([]byte, []int) {
	return file_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *MoveDoneReply) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_v1_response_proto protoreflect.FileDescriptor

var file_v1_response_proto_rawDesc = []byte{
	0x0a, 0x11, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xba, 0x01, 0x0a, 0x0f, 0x4d, 0x6f, 0x76, 0x65,
	0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x02, 0x72, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x02, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x65, 0x6c, 0x61, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x61,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x6f, 0x6e, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x60, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x08, 0x4d, 0x6f, 0x76,
	0x65, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x23, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x44,
	0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x1b, 0x5a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_response_proto_rawDescOnce sync.Once
	file_v1_response_proto_rawDescData = file_v1_response_proto_rawDesc
)

func file_v1_response_proto_rawDescGZIP() []byte {
	file_v1_response_proto_rawDescOnce.Do(func() {
		file_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_response_proto_rawDescData)
	})
	return file_v1_response_proto_rawDescData
}

var file_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_response_proto_goTypes = []interface{}{
	(*MoveDoneRequest)(nil), // 0: machine.service.v1.MoveDoneRequest
	(*MoveDoneReply)(nil),   // 1: machine.service.v1.MoveDoneReply
}
var file_v1_response_proto_depIdxs = []int32{
	0, // 0: machine.service.v1.Response.MoveDone:input_type -> machine.service.v1.MoveDoneRequest
	1, // 1: machine.service.v1.Response.MoveDone:output_type -> machine.service.v1.MoveDoneReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_response_proto_init() }
func file_v1_response_proto_init() {
	if File_v1_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveDoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveDoneReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_response_proto_goTypes,
		DependencyIndexes: file_v1_response_proto_depIdxs,
		MessageInfos:      file_v1_response_proto_msgTypes,
	}.Build()
	File_v1_response_proto = out.File
	file_v1_response_proto_rawDesc = nil
	file_v1_response_proto_goTypes = nil
	file_v1_response_proto_depIdxs = nil
}
