// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capture.proto

#include "capture.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace capture {
namespace service {
namespace v1 {
constexpr ReadOneRequest::ReadOneRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : id_(int64_t{0}){}
struct ReadOneRequestDefaultTypeInternal {
  constexpr ReadOneRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReadOneRequestDefaultTypeInternal() {}
  union {
    ReadOneRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReadOneRequestDefaultTypeInternal _ReadOneRequest_default_instance_;
constexpr ReadAllRequest::ReadAllRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct ReadAllRequestDefaultTypeInternal {
  constexpr ReadAllRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReadAllRequestDefaultTypeInternal() {}
  union {
    ReadAllRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReadAllRequestDefaultTypeInternal _ReadAllRequest_default_instance_;
constexpr ReadOneWithBinaryRequest::ReadOneWithBinaryRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : id_(int64_t{0}){}
struct ReadOneWithBinaryRequestDefaultTypeInternal {
  constexpr ReadOneWithBinaryRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReadOneWithBinaryRequestDefaultTypeInternal() {}
  union {
    ReadOneWithBinaryRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReadOneWithBinaryRequestDefaultTypeInternal _ReadOneWithBinaryRequest_default_instance_;
constexpr ReadAllWithBinaryRequest::ReadAllWithBinaryRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct ReadAllWithBinaryRequestDefaultTypeInternal {
  constexpr ReadAllWithBinaryRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReadAllWithBinaryRequestDefaultTypeInternal() {}
  union {
    ReadAllWithBinaryRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReadAllWithBinaryRequestDefaultTypeInternal _ReadAllWithBinaryRequest_default_instance_;
constexpr ReadOneWithBinaryAndCalAreaRequest::ReadOneWithBinaryAndCalAreaRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : id_(int64_t{0}){}
struct ReadOneWithBinaryAndCalAreaRequestDefaultTypeInternal {
  constexpr ReadOneWithBinaryAndCalAreaRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReadOneWithBinaryAndCalAreaRequestDefaultTypeInternal() {}
  union {
    ReadOneWithBinaryAndCalAreaRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReadOneWithBinaryAndCalAreaRequestDefaultTypeInternal _ReadOneWithBinaryAndCalAreaRequest_default_instance_;
constexpr ReadAllWithBinaryAndCalAreaRequest::ReadAllWithBinaryAndCalAreaRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct ReadAllWithBinaryAndCalAreaRequestDefaultTypeInternal {
  constexpr ReadAllWithBinaryAndCalAreaRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReadAllWithBinaryAndCalAreaRequestDefaultTypeInternal() {}
  union {
    ReadAllWithBinaryAndCalAreaRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReadAllWithBinaryAndCalAreaRequestDefaultTypeInternal _ReadAllWithBinaryAndCalAreaRequest_default_instance_;
constexpr ImageReply::ImageReply(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : image_(nullptr){}
struct ImageReplyDefaultTypeInternal {
  constexpr ImageReplyDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ImageReplyDefaultTypeInternal() {}
  union {
    ImageReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ImageReplyDefaultTypeInternal _ImageReply_default_instance_;
constexpr ImagesReply::ImagesReply(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : images_(){}
struct ImagesReplyDefaultTypeInternal {
  constexpr ImagesReplyDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ImagesReplyDefaultTypeInternal() {}
  union {
    ImagesReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ImagesReplyDefaultTypeInternal _ImagesReply_default_instance_;
constexpr ImageWithAreaReply::ImageWithAreaReply(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : image_(nullptr)
  , pixels_(int64_t{0})
  , area_(0){}
struct ImageWithAreaReplyDefaultTypeInternal {
  constexpr ImageWithAreaReplyDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ImageWithAreaReplyDefaultTypeInternal() {}
  union {
    ImageWithAreaReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ImageWithAreaReplyDefaultTypeInternal _ImageWithAreaReply_default_instance_;
constexpr ImagesWithAreaReply_Data::ImagesWithAreaReply_Data(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : image_(nullptr)
  , pixels_(int64_t{0})
  , area_(0){}
struct ImagesWithAreaReply_DataDefaultTypeInternal {
  constexpr ImagesWithAreaReply_DataDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ImagesWithAreaReply_DataDefaultTypeInternal() {}
  union {
    ImagesWithAreaReply_Data _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ImagesWithAreaReply_DataDefaultTypeInternal _ImagesWithAreaReply_Data_default_instance_;
constexpr ImagesWithAreaReply::ImagesWithAreaReply(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : data_(){}
struct ImagesWithAreaReplyDefaultTypeInternal {
  constexpr ImagesWithAreaReplyDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ImagesWithAreaReplyDefaultTypeInternal() {}
  union {
    ImagesWithAreaReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ImagesWithAreaReplyDefaultTypeInternal _ImagesWithAreaReply_default_instance_;
constexpr Image::Image(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : data_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct ImageDefaultTypeInternal {
  constexpr ImageDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ImageDefaultTypeInternal() {}
  union {
    Image _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ImageDefaultTypeInternal _Image_default_instance_;
}  // namespace v1
}  // namespace service
}  // namespace capture
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_capture_2eproto[12];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_capture_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_capture_2eproto = nullptr;

const uint32_t TableStruct_capture_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ReadOneRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ReadOneRequest, id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ReadAllRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ReadOneWithBinaryRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ReadOneWithBinaryRequest, id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ReadAllWithBinaryRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ReadOneWithBinaryAndCalAreaRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ReadOneWithBinaryAndCalAreaRequest, id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ReadAllWithBinaryAndCalAreaRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImageReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImageReply, image_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImagesReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImagesReply, images_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImageWithAreaReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImageWithAreaReply, image_),
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImageWithAreaReply, pixels_),
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImageWithAreaReply, area_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImagesWithAreaReply_Data, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImagesWithAreaReply_Data, image_),
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImagesWithAreaReply_Data, pixels_),
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImagesWithAreaReply_Data, area_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImagesWithAreaReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::ImagesWithAreaReply, data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::Image, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::capture::service::v1::Image, data_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::capture::service::v1::ReadOneRequest)},
  { 7, -1, -1, sizeof(::capture::service::v1::ReadAllRequest)},
  { 13, -1, -1, sizeof(::capture::service::v1::ReadOneWithBinaryRequest)},
  { 20, -1, -1, sizeof(::capture::service::v1::ReadAllWithBinaryRequest)},
  { 26, -1, -1, sizeof(::capture::service::v1::ReadOneWithBinaryAndCalAreaRequest)},
  { 33, -1, -1, sizeof(::capture::service::v1::ReadAllWithBinaryAndCalAreaRequest)},
  { 39, -1, -1, sizeof(::capture::service::v1::ImageReply)},
  { 46, -1, -1, sizeof(::capture::service::v1::ImagesReply)},
  { 53, -1, -1, sizeof(::capture::service::v1::ImageWithAreaReply)},
  { 62, -1, -1, sizeof(::capture::service::v1::ImagesWithAreaReply_Data)},
  { 71, -1, -1, sizeof(::capture::service::v1::ImagesWithAreaReply)},
  { 78, -1, -1, sizeof(::capture::service::v1::Image)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ReadOneRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ReadAllRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ReadOneWithBinaryRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ReadAllWithBinaryRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ReadOneWithBinaryAndCalAreaRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ReadAllWithBinaryAndCalAreaRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ImageReply_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ImagesReply_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ImageWithAreaReply_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ImagesWithAreaReply_Data_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_ImagesWithAreaReply_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::capture::service::v1::_Image_default_instance_),
};

const char descriptor_table_protodef_capture_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rcapture.proto\022\022capture.service.v1\"\034\n\016R"
  "eadOneRequest\022\n\n\002id\030\001 \001(\003\"\020\n\016ReadAllRequ"
  "est\"&\n\030ReadOneWithBinaryRequest\022\n\n\002id\030\001 "
  "\001(\003\"\032\n\030ReadAllWithBinaryRequest\"0\n\"ReadO"
  "neWithBinaryAndCalAreaRequest\022\n\n\002id\030\001 \001("
  "\003\"$\n\"ReadAllWithBinaryAndCalAreaRequest\""
  "6\n\nImageReply\022(\n\005image\030\001 \001(\0132\031.capture.s"
  "ervice.v1.Image\"8\n\013ImagesReply\022)\n\006images"
  "\030\001 \003(\0132\031.capture.service.v1.Image\"\\\n\022Ima"
  "geWithAreaReply\022(\n\005image\030\001 \001(\0132\031.capture"
  ".service.v1.Image\022\016\n\006pixels\030\002 \001(\003\022\014\n\004are"
  "a\030\003 \001(\001\"\241\001\n\023ImagesWithAreaReply\022:\n\004data\030"
  "\001 \003(\0132,.capture.service.v1.ImagesWithAre"
  "aReply.Data\032N\n\004Data\022(\n\005image\030\001 \001(\0132\031.cap"
  "ture.service.v1.Image\022\016\n\006pixels\030\002 \001(\003\022\014\n"
  "\004area\030\003 \001(\001\"\025\n\005Image\022\014\n\004data\030\001 \001(\0142\373\004\n\007C"
  "apture\022O\n\007ReadOne\022\".capture.service.v1.R"
  "eadOneRequest\032\036.capture.service.v1.Image"
  "Reply\"\000\022P\n\007ReadAll\022\".capture.service.v1."
  "ReadAllRequest\032\037.capture.service.v1.Imag"
  "esReply\"\000\022c\n\021ReadOneWithBinary\022,.capture"
  ".service.v1.ReadOneWithBinaryRequest\032\036.c"
  "apture.service.v1.ImageReply\"\000\022d\n\021ReadAl"
  "lWithBinary\022,.capture.service.v1.ReadAll"
  "WithBinaryRequest\032\037.capture.service.v1.I"
  "magesReply\"\000\022\177\n\033ReadOneWithBinaryAndCalA"
  "rea\0226.capture.service.v1.ReadOneWithBina"
  "ryAndCalAreaRequest\032&.capture.service.v1"
  ".ImageWithAreaReply\"\000\022\200\001\n\033ReadAllWithBin"
  "aryAndCalArea\0226.capture.service.v1.ReadA"
  "llWithBinaryAndCalAreaRequest\032\'.capture."
  "service.v1.ImagesWithAreaReply\"\000B\033Z\031api/"
  "capture/service/v1;v1b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_capture_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_capture_2eproto = {
  false, false, 1309, descriptor_table_protodef_capture_2eproto, "capture.proto", 
  &descriptor_table_capture_2eproto_once, nullptr, 0, 12,
  schemas, file_default_instances, TableStruct_capture_2eproto::offsets,
  file_level_metadata_capture_2eproto, file_level_enum_descriptors_capture_2eproto, file_level_service_descriptors_capture_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_capture_2eproto_getter() {
  return &descriptor_table_capture_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_capture_2eproto(&descriptor_table_capture_2eproto);
namespace capture {
namespace service {
namespace v1 {

// ===================================================================

class ReadOneRequest::_Internal {
 public:
};

ReadOneRequest::ReadOneRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ReadOneRequest)
}
ReadOneRequest::ReadOneRequest(const ReadOneRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ReadOneRequest)
}

inline void ReadOneRequest::SharedCtor() {
id_ = int64_t{0};
}

ReadOneRequest::~ReadOneRequest() {
  // @@protoc_insertion_point(destructor:capture.service.v1.ReadOneRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ReadOneRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ReadOneRequest::ArenaDtor(void* object) {
  ReadOneRequest* _this = reinterpret_cast< ReadOneRequest* >(object);
  (void)_this;
}
void ReadOneRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReadOneRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReadOneRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:capture.service.v1.ReadOneRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReadOneRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReadOneRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:capture.service.v1.ReadOneRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capture.service.v1.ReadOneRequest)
  return target;
}

size_t ReadOneRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capture.service.v1.ReadOneRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadOneRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ReadOneRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadOneRequest::GetClassData() const { return &_class_data_; }

void ReadOneRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ReadOneRequest *>(to)->MergeFrom(
      static_cast<const ReadOneRequest &>(from));
}


void ReadOneRequest::MergeFrom(const ReadOneRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capture.service.v1.ReadOneRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReadOneRequest::CopyFrom(const ReadOneRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capture.service.v1.ReadOneRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadOneRequest::IsInitialized() const {
  return true;
}

void ReadOneRequest::InternalSwap(ReadOneRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(id_, other->id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReadOneRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[0]);
}

// ===================================================================

class ReadAllRequest::_Internal {
 public:
};

ReadAllRequest::ReadAllRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ReadAllRequest)
}
ReadAllRequest::ReadAllRequest(const ReadAllRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ReadAllRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadAllRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadAllRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ReadAllRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[1]);
}

// ===================================================================

class ReadOneWithBinaryRequest::_Internal {
 public:
};

ReadOneWithBinaryRequest::ReadOneWithBinaryRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ReadOneWithBinaryRequest)
}
ReadOneWithBinaryRequest::ReadOneWithBinaryRequest(const ReadOneWithBinaryRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ReadOneWithBinaryRequest)
}

inline void ReadOneWithBinaryRequest::SharedCtor() {
id_ = int64_t{0};
}

ReadOneWithBinaryRequest::~ReadOneWithBinaryRequest() {
  // @@protoc_insertion_point(destructor:capture.service.v1.ReadOneWithBinaryRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ReadOneWithBinaryRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ReadOneWithBinaryRequest::ArenaDtor(void* object) {
  ReadOneWithBinaryRequest* _this = reinterpret_cast< ReadOneWithBinaryRequest* >(object);
  (void)_this;
}
void ReadOneWithBinaryRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReadOneWithBinaryRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReadOneWithBinaryRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:capture.service.v1.ReadOneWithBinaryRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReadOneWithBinaryRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReadOneWithBinaryRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:capture.service.v1.ReadOneWithBinaryRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capture.service.v1.ReadOneWithBinaryRequest)
  return target;
}

size_t ReadOneWithBinaryRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capture.service.v1.ReadOneWithBinaryRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadOneWithBinaryRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ReadOneWithBinaryRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadOneWithBinaryRequest::GetClassData() const { return &_class_data_; }

void ReadOneWithBinaryRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ReadOneWithBinaryRequest *>(to)->MergeFrom(
      static_cast<const ReadOneWithBinaryRequest &>(from));
}


void ReadOneWithBinaryRequest::MergeFrom(const ReadOneWithBinaryRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capture.service.v1.ReadOneWithBinaryRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReadOneWithBinaryRequest::CopyFrom(const ReadOneWithBinaryRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capture.service.v1.ReadOneWithBinaryRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadOneWithBinaryRequest::IsInitialized() const {
  return true;
}

void ReadOneWithBinaryRequest::InternalSwap(ReadOneWithBinaryRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(id_, other->id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReadOneWithBinaryRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[2]);
}

// ===================================================================

class ReadAllWithBinaryRequest::_Internal {
 public:
};

ReadAllWithBinaryRequest::ReadAllWithBinaryRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ReadAllWithBinaryRequest)
}
ReadAllWithBinaryRequest::ReadAllWithBinaryRequest(const ReadAllWithBinaryRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ReadAllWithBinaryRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadAllWithBinaryRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadAllWithBinaryRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ReadAllWithBinaryRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[3]);
}

// ===================================================================

class ReadOneWithBinaryAndCalAreaRequest::_Internal {
 public:
};

ReadOneWithBinaryAndCalAreaRequest::ReadOneWithBinaryAndCalAreaRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ReadOneWithBinaryAndCalAreaRequest)
}
ReadOneWithBinaryAndCalAreaRequest::ReadOneWithBinaryAndCalAreaRequest(const ReadOneWithBinaryAndCalAreaRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ReadOneWithBinaryAndCalAreaRequest)
}

inline void ReadOneWithBinaryAndCalAreaRequest::SharedCtor() {
id_ = int64_t{0};
}

ReadOneWithBinaryAndCalAreaRequest::~ReadOneWithBinaryAndCalAreaRequest() {
  // @@protoc_insertion_point(destructor:capture.service.v1.ReadOneWithBinaryAndCalAreaRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ReadOneWithBinaryAndCalAreaRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ReadOneWithBinaryAndCalAreaRequest::ArenaDtor(void* object) {
  ReadOneWithBinaryAndCalAreaRequest* _this = reinterpret_cast< ReadOneWithBinaryAndCalAreaRequest* >(object);
  (void)_this;
}
void ReadOneWithBinaryAndCalAreaRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReadOneWithBinaryAndCalAreaRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReadOneWithBinaryAndCalAreaRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:capture.service.v1.ReadOneWithBinaryAndCalAreaRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReadOneWithBinaryAndCalAreaRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReadOneWithBinaryAndCalAreaRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:capture.service.v1.ReadOneWithBinaryAndCalAreaRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capture.service.v1.ReadOneWithBinaryAndCalAreaRequest)
  return target;
}

size_t ReadOneWithBinaryAndCalAreaRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capture.service.v1.ReadOneWithBinaryAndCalAreaRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadOneWithBinaryAndCalAreaRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ReadOneWithBinaryAndCalAreaRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadOneWithBinaryAndCalAreaRequest::GetClassData() const { return &_class_data_; }

void ReadOneWithBinaryAndCalAreaRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ReadOneWithBinaryAndCalAreaRequest *>(to)->MergeFrom(
      static_cast<const ReadOneWithBinaryAndCalAreaRequest &>(from));
}


void ReadOneWithBinaryAndCalAreaRequest::MergeFrom(const ReadOneWithBinaryAndCalAreaRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capture.service.v1.ReadOneWithBinaryAndCalAreaRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReadOneWithBinaryAndCalAreaRequest::CopyFrom(const ReadOneWithBinaryAndCalAreaRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capture.service.v1.ReadOneWithBinaryAndCalAreaRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadOneWithBinaryAndCalAreaRequest::IsInitialized() const {
  return true;
}

void ReadOneWithBinaryAndCalAreaRequest::InternalSwap(ReadOneWithBinaryAndCalAreaRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(id_, other->id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReadOneWithBinaryAndCalAreaRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[4]);
}

// ===================================================================

class ReadAllWithBinaryAndCalAreaRequest::_Internal {
 public:
};

ReadAllWithBinaryAndCalAreaRequest::ReadAllWithBinaryAndCalAreaRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ReadAllWithBinaryAndCalAreaRequest)
}
ReadAllWithBinaryAndCalAreaRequest::ReadAllWithBinaryAndCalAreaRequest(const ReadAllWithBinaryAndCalAreaRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ReadAllWithBinaryAndCalAreaRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadAllWithBinaryAndCalAreaRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadAllWithBinaryAndCalAreaRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ReadAllWithBinaryAndCalAreaRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[5]);
}

// ===================================================================

class ImageReply::_Internal {
 public:
  static const ::capture::service::v1::Image& image(const ImageReply* msg);
};

const ::capture::service::v1::Image&
ImageReply::_Internal::image(const ImageReply* msg) {
  return *msg->image_;
}
ImageReply::ImageReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ImageReply)
}
ImageReply::ImageReply(const ImageReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_image()) {
    image_ = new ::capture::service::v1::Image(*from.image_);
  } else {
    image_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ImageReply)
}

inline void ImageReply::SharedCtor() {
image_ = nullptr;
}

ImageReply::~ImageReply() {
  // @@protoc_insertion_point(destructor:capture.service.v1.ImageReply)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ImageReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete image_;
}

void ImageReply::ArenaDtor(void* object) {
  ImageReply* _this = reinterpret_cast< ImageReply* >(object);
  (void)_this;
}
void ImageReply::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ImageReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ImageReply::Clear() {
// @@protoc_insertion_point(message_clear_start:capture.service.v1.ImageReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && image_ != nullptr) {
    delete image_;
  }
  image_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ImageReply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .capture.service.v1.Image image = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_image(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ImageReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:capture.service.v1.ImageReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .capture.service.v1.Image image = 1;
  if (this->_internal_has_image()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::image(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capture.service.v1.ImageReply)
  return target;
}

size_t ImageReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capture.service.v1.ImageReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .capture.service.v1.Image image = 1;
  if (this->_internal_has_image()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *image_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ImageReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ImageReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ImageReply::GetClassData() const { return &_class_data_; }

void ImageReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ImageReply *>(to)->MergeFrom(
      static_cast<const ImageReply &>(from));
}


void ImageReply::MergeFrom(const ImageReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capture.service.v1.ImageReply)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_image()) {
    _internal_mutable_image()->::capture::service::v1::Image::MergeFrom(from._internal_image());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ImageReply::CopyFrom(const ImageReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capture.service.v1.ImageReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImageReply::IsInitialized() const {
  return true;
}

void ImageReply::InternalSwap(ImageReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(image_, other->image_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ImageReply::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[6]);
}

// ===================================================================

class ImagesReply::_Internal {
 public:
};

ImagesReply::ImagesReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  images_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ImagesReply)
}
ImagesReply::ImagesReply(const ImagesReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      images_(from.images_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ImagesReply)
}

inline void ImagesReply::SharedCtor() {
}

ImagesReply::~ImagesReply() {
  // @@protoc_insertion_point(destructor:capture.service.v1.ImagesReply)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ImagesReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ImagesReply::ArenaDtor(void* object) {
  ImagesReply* _this = reinterpret_cast< ImagesReply* >(object);
  (void)_this;
}
void ImagesReply::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ImagesReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ImagesReply::Clear() {
// @@protoc_insertion_point(message_clear_start:capture.service.v1.ImagesReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  images_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ImagesReply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .capture.service.v1.Image images = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_images(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ImagesReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:capture.service.v1.ImagesReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .capture.service.v1.Image images = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_images_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_images(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capture.service.v1.ImagesReply)
  return target;
}

size_t ImagesReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capture.service.v1.ImagesReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .capture.service.v1.Image images = 1;
  total_size += 1UL * this->_internal_images_size();
  for (const auto& msg : this->images_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ImagesReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ImagesReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ImagesReply::GetClassData() const { return &_class_data_; }

void ImagesReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ImagesReply *>(to)->MergeFrom(
      static_cast<const ImagesReply &>(from));
}


void ImagesReply::MergeFrom(const ImagesReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capture.service.v1.ImagesReply)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  images_.MergeFrom(from.images_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ImagesReply::CopyFrom(const ImagesReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capture.service.v1.ImagesReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImagesReply::IsInitialized() const {
  return true;
}

void ImagesReply::InternalSwap(ImagesReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  images_.InternalSwap(&other->images_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ImagesReply::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[7]);
}

// ===================================================================

class ImageWithAreaReply::_Internal {
 public:
  static const ::capture::service::v1::Image& image(const ImageWithAreaReply* msg);
};

const ::capture::service::v1::Image&
ImageWithAreaReply::_Internal::image(const ImageWithAreaReply* msg) {
  return *msg->image_;
}
ImageWithAreaReply::ImageWithAreaReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ImageWithAreaReply)
}
ImageWithAreaReply::ImageWithAreaReply(const ImageWithAreaReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_image()) {
    image_ = new ::capture::service::v1::Image(*from.image_);
  } else {
    image_ = nullptr;
  }
  ::memcpy(&pixels_, &from.pixels_,
    static_cast<size_t>(reinterpret_cast<char*>(&area_) -
    reinterpret_cast<char*>(&pixels_)) + sizeof(area_));
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ImageWithAreaReply)
}

inline void ImageWithAreaReply::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&image_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&area_) -
    reinterpret_cast<char*>(&image_)) + sizeof(area_));
}

ImageWithAreaReply::~ImageWithAreaReply() {
  // @@protoc_insertion_point(destructor:capture.service.v1.ImageWithAreaReply)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ImageWithAreaReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete image_;
}

void ImageWithAreaReply::ArenaDtor(void* object) {
  ImageWithAreaReply* _this = reinterpret_cast< ImageWithAreaReply* >(object);
  (void)_this;
}
void ImageWithAreaReply::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ImageWithAreaReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ImageWithAreaReply::Clear() {
// @@protoc_insertion_point(message_clear_start:capture.service.v1.ImageWithAreaReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && image_ != nullptr) {
    delete image_;
  }
  image_ = nullptr;
  ::memset(&pixels_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&area_) -
      reinterpret_cast<char*>(&pixels_)) + sizeof(area_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ImageWithAreaReply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .capture.service.v1.Image image = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_image(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 pixels = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          pixels_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double area = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          area_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ImageWithAreaReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:capture.service.v1.ImageWithAreaReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .capture.service.v1.Image image = 1;
  if (this->_internal_has_image()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::image(this), target, stream);
  }

  // int64 pixels = 2;
  if (this->_internal_pixels() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_pixels(), target);
  }

  // double area = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_area = this->_internal_area();
  uint64_t raw_area;
  memcpy(&raw_area, &tmp_area, sizeof(tmp_area));
  if (raw_area != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_area(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capture.service.v1.ImageWithAreaReply)
  return target;
}

size_t ImageWithAreaReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capture.service.v1.ImageWithAreaReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .capture.service.v1.Image image = 1;
  if (this->_internal_has_image()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *image_);
  }

  // int64 pixels = 2;
  if (this->_internal_pixels() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_pixels());
  }

  // double area = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_area = this->_internal_area();
  uint64_t raw_area;
  memcpy(&raw_area, &tmp_area, sizeof(tmp_area));
  if (raw_area != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ImageWithAreaReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ImageWithAreaReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ImageWithAreaReply::GetClassData() const { return &_class_data_; }

void ImageWithAreaReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ImageWithAreaReply *>(to)->MergeFrom(
      static_cast<const ImageWithAreaReply &>(from));
}


void ImageWithAreaReply::MergeFrom(const ImageWithAreaReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capture.service.v1.ImageWithAreaReply)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_image()) {
    _internal_mutable_image()->::capture::service::v1::Image::MergeFrom(from._internal_image());
  }
  if (from._internal_pixels() != 0) {
    _internal_set_pixels(from._internal_pixels());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_area = from._internal_area();
  uint64_t raw_area;
  memcpy(&raw_area, &tmp_area, sizeof(tmp_area));
  if (raw_area != 0) {
    _internal_set_area(from._internal_area());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ImageWithAreaReply::CopyFrom(const ImageWithAreaReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capture.service.v1.ImageWithAreaReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImageWithAreaReply::IsInitialized() const {
  return true;
}

void ImageWithAreaReply::InternalSwap(ImageWithAreaReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ImageWithAreaReply, area_)
      + sizeof(ImageWithAreaReply::area_)
      - PROTOBUF_FIELD_OFFSET(ImageWithAreaReply, image_)>(
          reinterpret_cast<char*>(&image_),
          reinterpret_cast<char*>(&other->image_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ImageWithAreaReply::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[8]);
}

// ===================================================================

class ImagesWithAreaReply_Data::_Internal {
 public:
  static const ::capture::service::v1::Image& image(const ImagesWithAreaReply_Data* msg);
};

const ::capture::service::v1::Image&
ImagesWithAreaReply_Data::_Internal::image(const ImagesWithAreaReply_Data* msg) {
  return *msg->image_;
}
ImagesWithAreaReply_Data::ImagesWithAreaReply_Data(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ImagesWithAreaReply.Data)
}
ImagesWithAreaReply_Data::ImagesWithAreaReply_Data(const ImagesWithAreaReply_Data& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_image()) {
    image_ = new ::capture::service::v1::Image(*from.image_);
  } else {
    image_ = nullptr;
  }
  ::memcpy(&pixels_, &from.pixels_,
    static_cast<size_t>(reinterpret_cast<char*>(&area_) -
    reinterpret_cast<char*>(&pixels_)) + sizeof(area_));
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ImagesWithAreaReply.Data)
}

inline void ImagesWithAreaReply_Data::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&image_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&area_) -
    reinterpret_cast<char*>(&image_)) + sizeof(area_));
}

ImagesWithAreaReply_Data::~ImagesWithAreaReply_Data() {
  // @@protoc_insertion_point(destructor:capture.service.v1.ImagesWithAreaReply.Data)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ImagesWithAreaReply_Data::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete image_;
}

void ImagesWithAreaReply_Data::ArenaDtor(void* object) {
  ImagesWithAreaReply_Data* _this = reinterpret_cast< ImagesWithAreaReply_Data* >(object);
  (void)_this;
}
void ImagesWithAreaReply_Data::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ImagesWithAreaReply_Data::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ImagesWithAreaReply_Data::Clear() {
// @@protoc_insertion_point(message_clear_start:capture.service.v1.ImagesWithAreaReply.Data)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && image_ != nullptr) {
    delete image_;
  }
  image_ = nullptr;
  ::memset(&pixels_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&area_) -
      reinterpret_cast<char*>(&pixels_)) + sizeof(area_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ImagesWithAreaReply_Data::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .capture.service.v1.Image image = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_image(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 pixels = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          pixels_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double area = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          area_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ImagesWithAreaReply_Data::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:capture.service.v1.ImagesWithAreaReply.Data)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .capture.service.v1.Image image = 1;
  if (this->_internal_has_image()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::image(this), target, stream);
  }

  // int64 pixels = 2;
  if (this->_internal_pixels() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_pixels(), target);
  }

  // double area = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_area = this->_internal_area();
  uint64_t raw_area;
  memcpy(&raw_area, &tmp_area, sizeof(tmp_area));
  if (raw_area != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_area(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capture.service.v1.ImagesWithAreaReply.Data)
  return target;
}

size_t ImagesWithAreaReply_Data::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capture.service.v1.ImagesWithAreaReply.Data)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .capture.service.v1.Image image = 1;
  if (this->_internal_has_image()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *image_);
  }

  // int64 pixels = 2;
  if (this->_internal_pixels() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_pixels());
  }

  // double area = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_area = this->_internal_area();
  uint64_t raw_area;
  memcpy(&raw_area, &tmp_area, sizeof(tmp_area));
  if (raw_area != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ImagesWithAreaReply_Data::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ImagesWithAreaReply_Data::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ImagesWithAreaReply_Data::GetClassData() const { return &_class_data_; }

void ImagesWithAreaReply_Data::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ImagesWithAreaReply_Data *>(to)->MergeFrom(
      static_cast<const ImagesWithAreaReply_Data &>(from));
}


void ImagesWithAreaReply_Data::MergeFrom(const ImagesWithAreaReply_Data& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capture.service.v1.ImagesWithAreaReply.Data)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_image()) {
    _internal_mutable_image()->::capture::service::v1::Image::MergeFrom(from._internal_image());
  }
  if (from._internal_pixels() != 0) {
    _internal_set_pixels(from._internal_pixels());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_area = from._internal_area();
  uint64_t raw_area;
  memcpy(&raw_area, &tmp_area, sizeof(tmp_area));
  if (raw_area != 0) {
    _internal_set_area(from._internal_area());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ImagesWithAreaReply_Data::CopyFrom(const ImagesWithAreaReply_Data& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capture.service.v1.ImagesWithAreaReply.Data)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImagesWithAreaReply_Data::IsInitialized() const {
  return true;
}

void ImagesWithAreaReply_Data::InternalSwap(ImagesWithAreaReply_Data* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ImagesWithAreaReply_Data, area_)
      + sizeof(ImagesWithAreaReply_Data::area_)
      - PROTOBUF_FIELD_OFFSET(ImagesWithAreaReply_Data, image_)>(
          reinterpret_cast<char*>(&image_),
          reinterpret_cast<char*>(&other->image_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ImagesWithAreaReply_Data::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[9]);
}

// ===================================================================

class ImagesWithAreaReply::_Internal {
 public:
};

ImagesWithAreaReply::ImagesWithAreaReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  data_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.ImagesWithAreaReply)
}
ImagesWithAreaReply::ImagesWithAreaReply(const ImagesWithAreaReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      data_(from.data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.ImagesWithAreaReply)
}

inline void ImagesWithAreaReply::SharedCtor() {
}

ImagesWithAreaReply::~ImagesWithAreaReply() {
  // @@protoc_insertion_point(destructor:capture.service.v1.ImagesWithAreaReply)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ImagesWithAreaReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ImagesWithAreaReply::ArenaDtor(void* object) {
  ImagesWithAreaReply* _this = reinterpret_cast< ImagesWithAreaReply* >(object);
  (void)_this;
}
void ImagesWithAreaReply::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ImagesWithAreaReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ImagesWithAreaReply::Clear() {
// @@protoc_insertion_point(message_clear_start:capture.service.v1.ImagesWithAreaReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ImagesWithAreaReply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .capture.service.v1.ImagesWithAreaReply.Data data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_data(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ImagesWithAreaReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:capture.service.v1.ImagesWithAreaReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .capture.service.v1.ImagesWithAreaReply.Data data = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_data_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_data(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capture.service.v1.ImagesWithAreaReply)
  return target;
}

size_t ImagesWithAreaReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capture.service.v1.ImagesWithAreaReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .capture.service.v1.ImagesWithAreaReply.Data data = 1;
  total_size += 1UL * this->_internal_data_size();
  for (const auto& msg : this->data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ImagesWithAreaReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ImagesWithAreaReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ImagesWithAreaReply::GetClassData() const { return &_class_data_; }

void ImagesWithAreaReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ImagesWithAreaReply *>(to)->MergeFrom(
      static_cast<const ImagesWithAreaReply &>(from));
}


void ImagesWithAreaReply::MergeFrom(const ImagesWithAreaReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capture.service.v1.ImagesWithAreaReply)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ImagesWithAreaReply::CopyFrom(const ImagesWithAreaReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capture.service.v1.ImagesWithAreaReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImagesWithAreaReply::IsInitialized() const {
  return true;
}

void ImagesWithAreaReply::InternalSwap(ImagesWithAreaReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  data_.InternalSwap(&other->data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ImagesWithAreaReply::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[10]);
}

// ===================================================================

class Image::_Internal {
 public:
};

Image::Image(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:capture.service.v1.Image)
}
Image::Image(const Image& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_data(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:capture.service.v1.Image)
}

inline void Image::SharedCtor() {
data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Image::~Image() {
  // @@protoc_insertion_point(destructor:capture.service.v1.Image)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Image::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  data_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Image::ArenaDtor(void* object) {
  Image* _this = reinterpret_cast< Image* >(object);
  (void)_this;
}
void Image::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Image::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Image::Clear() {
// @@protoc_insertion_point(message_clear_start:capture.service.v1.Image)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Image::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_data();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Image::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:capture.service.v1.Image)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capture.service.v1.Image)
  return target;
}

size_t Image::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capture.service.v1.Image)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Image::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Image::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Image::GetClassData() const { return &_class_data_; }

void Image::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Image *>(to)->MergeFrom(
      static_cast<const Image &>(from));
}


void Image::MergeFrom(const Image& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capture.service.v1.Image)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _internal_set_data(from._internal_data());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Image::CopyFrom(const Image& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capture.service.v1.Image)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Image::IsInitialized() const {
  return true;
}

void Image::InternalSwap(Image* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &data_, lhs_arena,
      &other->data_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Image::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_capture_2eproto_getter, &descriptor_table_capture_2eproto_once,
      file_level_metadata_capture_2eproto[11]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace service
}  // namespace capture
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::capture::service::v1::ReadOneRequest* Arena::CreateMaybeMessage< ::capture::service::v1::ReadOneRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ReadOneRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ReadAllRequest* Arena::CreateMaybeMessage< ::capture::service::v1::ReadAllRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ReadAllRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ReadOneWithBinaryRequest* Arena::CreateMaybeMessage< ::capture::service::v1::ReadOneWithBinaryRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ReadOneWithBinaryRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ReadAllWithBinaryRequest* Arena::CreateMaybeMessage< ::capture::service::v1::ReadAllWithBinaryRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ReadAllWithBinaryRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ReadOneWithBinaryAndCalAreaRequest* Arena::CreateMaybeMessage< ::capture::service::v1::ReadOneWithBinaryAndCalAreaRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ReadOneWithBinaryAndCalAreaRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ReadAllWithBinaryAndCalAreaRequest* Arena::CreateMaybeMessage< ::capture::service::v1::ReadAllWithBinaryAndCalAreaRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ReadAllWithBinaryAndCalAreaRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ImageReply* Arena::CreateMaybeMessage< ::capture::service::v1::ImageReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ImageReply >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ImagesReply* Arena::CreateMaybeMessage< ::capture::service::v1::ImagesReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ImagesReply >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ImageWithAreaReply* Arena::CreateMaybeMessage< ::capture::service::v1::ImageWithAreaReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ImageWithAreaReply >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ImagesWithAreaReply_Data* Arena::CreateMaybeMessage< ::capture::service::v1::ImagesWithAreaReply_Data >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ImagesWithAreaReply_Data >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::ImagesWithAreaReply* Arena::CreateMaybeMessage< ::capture::service::v1::ImagesWithAreaReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::ImagesWithAreaReply >(arena);
}
template<> PROTOBUF_NOINLINE ::capture::service::v1::Image* Arena::CreateMaybeMessage< ::capture::service::v1::Image >(Arena* arena) {
  return Arena::CreateMessageInternal< ::capture::service::v1::Image >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
