// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"htp-platform/app/machine/service/internal/data/ent/capturelog"
	"htp-platform/app/machine/service/internal/data/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CaptureLogQuery is the builder for querying CaptureLog entities.
type CaptureLogQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.CaptureLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CaptureLogQuery builder.
func (clq *CaptureLogQuery) Where(ps ...predicate.CaptureLog) *CaptureLogQuery {
	clq.predicates = append(clq.predicates, ps...)
	return clq
}

// Limit adds a limit step to the query.
func (clq *CaptureLogQuery) Limit(limit int) *CaptureLogQuery {
	clq.limit = &limit
	return clq
}

// Offset adds an offset step to the query.
func (clq *CaptureLogQuery) Offset(offset int) *CaptureLogQuery {
	clq.offset = &offset
	return clq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (clq *CaptureLogQuery) Unique(unique bool) *CaptureLogQuery {
	clq.unique = &unique
	return clq
}

// Order adds an order step to the query.
func (clq *CaptureLogQuery) Order(o ...OrderFunc) *CaptureLogQuery {
	clq.order = append(clq.order, o...)
	return clq
}

// First returns the first CaptureLog entity from the query.
// Returns a *NotFoundError when no CaptureLog was found.
func (clq *CaptureLogQuery) First(ctx context.Context) (*CaptureLog, error) {
	nodes, err := clq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{capturelog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (clq *CaptureLogQuery) FirstX(ctx context.Context) *CaptureLog {
	node, err := clq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CaptureLog ID from the query.
// Returns a *NotFoundError when no CaptureLog ID was found.
func (clq *CaptureLogQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = clq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{capturelog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (clq *CaptureLogQuery) FirstIDX(ctx context.Context) int64 {
	id, err := clq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CaptureLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one CaptureLog entity is not found.
// Returns a *NotFoundError when no CaptureLog entities are found.
func (clq *CaptureLogQuery) Only(ctx context.Context) (*CaptureLog, error) {
	nodes, err := clq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{capturelog.Label}
	default:
		return nil, &NotSingularError{capturelog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (clq *CaptureLogQuery) OnlyX(ctx context.Context) *CaptureLog {
	node, err := clq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CaptureLog ID in the query.
// Returns a *NotSingularError when exactly one CaptureLog ID is not found.
// Returns a *NotFoundError when no entities are found.
func (clq *CaptureLogQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = clq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{capturelog.Label}
	default:
		err = &NotSingularError{capturelog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (clq *CaptureLogQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := clq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CaptureLogs.
func (clq *CaptureLogQuery) All(ctx context.Context) ([]*CaptureLog, error) {
	if err := clq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return clq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (clq *CaptureLogQuery) AllX(ctx context.Context) []*CaptureLog {
	nodes, err := clq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CaptureLog IDs.
func (clq *CaptureLogQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := clq.Select(capturelog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (clq *CaptureLogQuery) IDsX(ctx context.Context) []int64 {
	ids, err := clq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (clq *CaptureLogQuery) Count(ctx context.Context) (int, error) {
	if err := clq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return clq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (clq *CaptureLogQuery) CountX(ctx context.Context) int {
	count, err := clq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (clq *CaptureLogQuery) Exist(ctx context.Context) (bool, error) {
	if err := clq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return clq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (clq *CaptureLogQuery) ExistX(ctx context.Context) bool {
	exist, err := clq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CaptureLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (clq *CaptureLogQuery) Clone() *CaptureLogQuery {
	if clq == nil {
		return nil
	}
	return &CaptureLogQuery{
		config:     clq.config,
		limit:      clq.limit,
		offset:     clq.offset,
		order:      append([]OrderFunc{}, clq.order...),
		predicates: append([]predicate.CaptureLog{}, clq.predicates...),
		// clone intermediate query.
		sql:  clq.sql.Clone(),
		path: clq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MachineID int64 `json:"machine_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CaptureLog.Query().
//		GroupBy(capturelog.FieldMachineID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (clq *CaptureLogQuery) GroupBy(field string, fields ...string) *CaptureLogGroupBy {
	group := &CaptureLogGroupBy{config: clq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return clq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MachineID int64 `json:"machine_id,omitempty"`
//	}
//
//	client.CaptureLog.Query().
//		Select(capturelog.FieldMachineID).
//		Scan(ctx, &v)
//
func (clq *CaptureLogQuery) Select(fields ...string) *CaptureLogSelect {
	clq.fields = append(clq.fields, fields...)
	return &CaptureLogSelect{CaptureLogQuery: clq}
}

func (clq *CaptureLogQuery) prepareQuery(ctx context.Context) error {
	for _, f := range clq.fields {
		if !capturelog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if clq.path != nil {
		prev, err := clq.path(ctx)
		if err != nil {
			return err
		}
		clq.sql = prev
	}
	return nil
}

func (clq *CaptureLogQuery) sqlAll(ctx context.Context) ([]*CaptureLog, error) {
	var (
		nodes = []*CaptureLog{}
		_spec = clq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &CaptureLog{config: clq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, clq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (clq *CaptureLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := clq.querySpec()
	_spec.Node.Columns = clq.fields
	if len(clq.fields) > 0 {
		_spec.Unique = clq.unique != nil && *clq.unique
	}
	return sqlgraph.CountNodes(ctx, clq.driver, _spec)
}

func (clq *CaptureLogQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := clq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (clq *CaptureLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   capturelog.Table,
			Columns: capturelog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: capturelog.FieldID,
			},
		},
		From:   clq.sql,
		Unique: true,
	}
	if unique := clq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := clq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, capturelog.FieldID)
		for i := range fields {
			if fields[i] != capturelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := clq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := clq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := clq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := clq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (clq *CaptureLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(clq.driver.Dialect())
	t1 := builder.Table(capturelog.Table)
	columns := clq.fields
	if len(columns) == 0 {
		columns = capturelog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if clq.sql != nil {
		selector = clq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if clq.unique != nil && *clq.unique {
		selector.Distinct()
	}
	for _, p := range clq.predicates {
		p(selector)
	}
	for _, p := range clq.order {
		p(selector)
	}
	if offset := clq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := clq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CaptureLogGroupBy is the group-by builder for CaptureLog entities.
type CaptureLogGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (clgb *CaptureLogGroupBy) Aggregate(fns ...AggregateFunc) *CaptureLogGroupBy {
	clgb.fns = append(clgb.fns, fns...)
	return clgb
}

// Scan applies the group-by query and scans the result into the given value.
func (clgb *CaptureLogGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := clgb.path(ctx)
	if err != nil {
		return err
	}
	clgb.sql = query
	return clgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (clgb *CaptureLogGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := clgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (clgb *CaptureLogGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(clgb.fields) > 1 {
		return nil, errors.New("ent: CaptureLogGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := clgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (clgb *CaptureLogGroupBy) StringsX(ctx context.Context) []string {
	v, err := clgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (clgb *CaptureLogGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = clgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{capturelog.Label}
	default:
		err = fmt.Errorf("ent: CaptureLogGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (clgb *CaptureLogGroupBy) StringX(ctx context.Context) string {
	v, err := clgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (clgb *CaptureLogGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(clgb.fields) > 1 {
		return nil, errors.New("ent: CaptureLogGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := clgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (clgb *CaptureLogGroupBy) IntsX(ctx context.Context) []int {
	v, err := clgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (clgb *CaptureLogGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = clgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{capturelog.Label}
	default:
		err = fmt.Errorf("ent: CaptureLogGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (clgb *CaptureLogGroupBy) IntX(ctx context.Context) int {
	v, err := clgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (clgb *CaptureLogGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(clgb.fields) > 1 {
		return nil, errors.New("ent: CaptureLogGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := clgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (clgb *CaptureLogGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := clgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (clgb *CaptureLogGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = clgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{capturelog.Label}
	default:
		err = fmt.Errorf("ent: CaptureLogGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (clgb *CaptureLogGroupBy) Float64X(ctx context.Context) float64 {
	v, err := clgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (clgb *CaptureLogGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(clgb.fields) > 1 {
		return nil, errors.New("ent: CaptureLogGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := clgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (clgb *CaptureLogGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := clgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (clgb *CaptureLogGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = clgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{capturelog.Label}
	default:
		err = fmt.Errorf("ent: CaptureLogGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (clgb *CaptureLogGroupBy) BoolX(ctx context.Context) bool {
	v, err := clgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (clgb *CaptureLogGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range clgb.fields {
		if !capturelog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := clgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := clgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (clgb *CaptureLogGroupBy) sqlQuery() *sql.Selector {
	selector := clgb.sql.Select()
	aggregation := make([]string, 0, len(clgb.fns))
	for _, fn := range clgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(clgb.fields)+len(clgb.fns))
		for _, f := range clgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(clgb.fields...)...)
}

// CaptureLogSelect is the builder for selecting fields of CaptureLog entities.
type CaptureLogSelect struct {
	*CaptureLogQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cls *CaptureLogSelect) Scan(ctx context.Context, v interface{}) error {
	if err := cls.prepareQuery(ctx); err != nil {
		return err
	}
	cls.sql = cls.CaptureLogQuery.sqlQuery(ctx)
	return cls.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cls *CaptureLogSelect) ScanX(ctx context.Context, v interface{}) {
	if err := cls.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (cls *CaptureLogSelect) Strings(ctx context.Context) ([]string, error) {
	if len(cls.fields) > 1 {
		return nil, errors.New("ent: CaptureLogSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := cls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cls *CaptureLogSelect) StringsX(ctx context.Context) []string {
	v, err := cls.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (cls *CaptureLogSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cls.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{capturelog.Label}
	default:
		err = fmt.Errorf("ent: CaptureLogSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cls *CaptureLogSelect) StringX(ctx context.Context) string {
	v, err := cls.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (cls *CaptureLogSelect) Ints(ctx context.Context) ([]int, error) {
	if len(cls.fields) > 1 {
		return nil, errors.New("ent: CaptureLogSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := cls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cls *CaptureLogSelect) IntsX(ctx context.Context) []int {
	v, err := cls.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (cls *CaptureLogSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cls.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{capturelog.Label}
	default:
		err = fmt.Errorf("ent: CaptureLogSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cls *CaptureLogSelect) IntX(ctx context.Context) int {
	v, err := cls.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (cls *CaptureLogSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(cls.fields) > 1 {
		return nil, errors.New("ent: CaptureLogSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := cls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cls *CaptureLogSelect) Float64sX(ctx context.Context) []float64 {
	v, err := cls.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (cls *CaptureLogSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cls.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{capturelog.Label}
	default:
		err = fmt.Errorf("ent: CaptureLogSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cls *CaptureLogSelect) Float64X(ctx context.Context) float64 {
	v, err := cls.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (cls *CaptureLogSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(cls.fields) > 1 {
		return nil, errors.New("ent: CaptureLogSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := cls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cls *CaptureLogSelect) BoolsX(ctx context.Context) []bool {
	v, err := cls.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (cls *CaptureLogSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cls.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{capturelog.Label}
	default:
		err = fmt.Errorf("ent: CaptureLogSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cls *CaptureLogSelect) BoolX(ctx context.Context) bool {
	v, err := cls.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cls *CaptureLogSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cls.sql.Query()
	if err := cls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
