// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: robot.proto

#include "robot.pb.h"
#include "robot.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace machine {
namespace robot {
namespace v1 {

static const char* Robot_method_names[] = {
  "/machine.robot.v1.Robot/AppendCoordinate",
  "/machine.robot.v1.Robot/Zero",
  "/machine.robot.v1.Robot/GetMotorStatus",
};

std::unique_ptr< Robot::Stub> Robot::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Robot::Stub> stub(new Robot::Stub(channel, options));
  return stub;
}

Robot::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AppendCoordinate_(Robot_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Zero_(Robot_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMotorStatus_(Robot_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Robot::Stub::AppendCoordinate(::grpc::ClientContext* context, const ::machine::robot::v1::CoordinateRequest& request, ::machine::robot::v1::CoordinateReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::machine::robot::v1::CoordinateRequest, ::machine::robot::v1::CoordinateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AppendCoordinate_, context, request, response);
}

void Robot::Stub::async::AppendCoordinate(::grpc::ClientContext* context, const ::machine::robot::v1::CoordinateRequest* request, ::machine::robot::v1::CoordinateReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::machine::robot::v1::CoordinateRequest, ::machine::robot::v1::CoordinateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendCoordinate_, context, request, response, std::move(f));
}

void Robot::Stub::async::AppendCoordinate(::grpc::ClientContext* context, const ::machine::robot::v1::CoordinateRequest* request, ::machine::robot::v1::CoordinateReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendCoordinate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::machine::robot::v1::CoordinateReply>* Robot::Stub::PrepareAsyncAppendCoordinateRaw(::grpc::ClientContext* context, const ::machine::robot::v1::CoordinateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::machine::robot::v1::CoordinateReply, ::machine::robot::v1::CoordinateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AppendCoordinate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::machine::robot::v1::CoordinateReply>* Robot::Stub::AsyncAppendCoordinateRaw(::grpc::ClientContext* context, const ::machine::robot::v1::CoordinateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAppendCoordinateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Robot::Stub::Zero(::grpc::ClientContext* context, const ::machine::robot::v1::ZeroRequest& request, ::machine::robot::v1::ZeroReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::machine::robot::v1::ZeroRequest, ::machine::robot::v1::ZeroReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Zero_, context, request, response);
}

void Robot::Stub::async::Zero(::grpc::ClientContext* context, const ::machine::robot::v1::ZeroRequest* request, ::machine::robot::v1::ZeroReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::machine::robot::v1::ZeroRequest, ::machine::robot::v1::ZeroReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Zero_, context, request, response, std::move(f));
}

void Robot::Stub::async::Zero(::grpc::ClientContext* context, const ::machine::robot::v1::ZeroRequest* request, ::machine::robot::v1::ZeroReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Zero_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::machine::robot::v1::ZeroReply>* Robot::Stub::PrepareAsyncZeroRaw(::grpc::ClientContext* context, const ::machine::robot::v1::ZeroRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::machine::robot::v1::ZeroReply, ::machine::robot::v1::ZeroRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Zero_, context, request);
}

::grpc::ClientAsyncResponseReader< ::machine::robot::v1::ZeroReply>* Robot::Stub::AsyncZeroRaw(::grpc::ClientContext* context, const ::machine::robot::v1::ZeroRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncZeroRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Robot::Stub::GetMotorStatus(::grpc::ClientContext* context, const ::machine::robot::v1::MotorInfoRequest& request, ::machine::robot::v1::MotorInfoReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::machine::robot::v1::MotorInfoRequest, ::machine::robot::v1::MotorInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMotorStatus_, context, request, response);
}

void Robot::Stub::async::GetMotorStatus(::grpc::ClientContext* context, const ::machine::robot::v1::MotorInfoRequest* request, ::machine::robot::v1::MotorInfoReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::machine::robot::v1::MotorInfoRequest, ::machine::robot::v1::MotorInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMotorStatus_, context, request, response, std::move(f));
}

void Robot::Stub::async::GetMotorStatus(::grpc::ClientContext* context, const ::machine::robot::v1::MotorInfoRequest* request, ::machine::robot::v1::MotorInfoReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMotorStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::machine::robot::v1::MotorInfoReply>* Robot::Stub::PrepareAsyncGetMotorStatusRaw(::grpc::ClientContext* context, const ::machine::robot::v1::MotorInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::machine::robot::v1::MotorInfoReply, ::machine::robot::v1::MotorInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMotorStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::machine::robot::v1::MotorInfoReply>* Robot::Stub::AsyncGetMotorStatusRaw(::grpc::ClientContext* context, const ::machine::robot::v1::MotorInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMotorStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

Robot::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Robot_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Robot::Service, ::machine::robot::v1::CoordinateRequest, ::machine::robot::v1::CoordinateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Robot::Service* service,
             ::grpc::ServerContext* ctx,
             const ::machine::robot::v1::CoordinateRequest* req,
             ::machine::robot::v1::CoordinateReply* resp) {
               return service->AppendCoordinate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Robot_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Robot::Service, ::machine::robot::v1::ZeroRequest, ::machine::robot::v1::ZeroReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Robot::Service* service,
             ::grpc::ServerContext* ctx,
             const ::machine::robot::v1::ZeroRequest* req,
             ::machine::robot::v1::ZeroReply* resp) {
               return service->Zero(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Robot_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Robot::Service, ::machine::robot::v1::MotorInfoRequest, ::machine::robot::v1::MotorInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Robot::Service* service,
             ::grpc::ServerContext* ctx,
             const ::machine::robot::v1::MotorInfoRequest* req,
             ::machine::robot::v1::MotorInfoReply* resp) {
               return service->GetMotorStatus(ctx, req, resp);
             }, this)));
}

Robot::Service::~Service() {
}

::grpc::Status Robot::Service::AppendCoordinate(::grpc::ServerContext* context, const ::machine::robot::v1::CoordinateRequest* request, ::machine::robot::v1::CoordinateReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Robot::Service::Zero(::grpc::ServerContext* context, const ::machine::robot::v1::ZeroRequest* request, ::machine::robot::v1::ZeroReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Robot::Service::GetMotorStatus(::grpc::ServerContext* context, const ::machine::robot::v1::MotorInfoRequest* request, ::machine::robot::v1::MotorInfoReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace machine
}  // namespace robot
}  // namespace v1

