//
// Created by Homin Su on 2022/2/19.
//

#ifndef HTP_PLATFORM_MACHINE_ROBOT_INTERNAL_SERVER_ROBOT_SERVER_H_
#define HTP_PLATFORM_MACHINE_ROBOT_INTERNAL_SERVER_ROBOT_SERVER_H_



class RobotServer {

};



#endif //HTP_PLATFORM_MACHINE_ROBOT_INTERNAL_SERVER_ROBOT_SERVER_H_
